blank_issues_enabled: false
contact_links:
  - name: Other question or discussion
    url: https://github.com/LucasOscarSimon/ejercicios-semana-1-ui/discussions
    about: Use GitHub Discussions for general topics
